# Default values for guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

guestbook:
  name: guestbook
  ports:
    name: http-server
    containerPort: 3000
  replicaCount: 1
  labels:
    app: guestbook
  image:
    repository: ibmcom/guestbook
    pullPolicy: Always
    tag: v1
  service:
    type: LoadBalancer

redismaster:
  name: redis-master
  ports:
    name: redis-server
    containerPort: 6379
  replicaCount: 1
  labels:
    app: redis
    role: master
  image:
    repository: redis
    pullPolicy: Always
    tag: 5.0.5
  service:
    type: ClusterIP

redisslave:
  name: redis-slave
  ports:
    name: redis-server
    containerPort: 6379
  replicaCount: 2
  labels:
    app: redis
    role: slave
  image:
    repository: clouddragons/redis-slave
    pullPolicy: Always
    tag: v1
  service:
    type: ClusterIP


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingress:
  enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling: {}

nodeSelector: {}

tolerations: []

affinity: {}
