apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.guestbook.name }}
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
    {{- with .Values.guestbook.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.guestbook.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "guestbook.selectorLabels" . | nindent 6 }}
      {{- with .Values.guestbook.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "guestbook.selectorLabels" . | nindent 8 }}
        {{- with .Values.guestbook.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "guestbook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.guestbook.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.guestbook.image.repository }}:{{ .Values.guestbook.image.tag }}"
          imagePullPolicy: {{ .Values.guestbook.image.pullPolicy }}
          ports:
            - name: {{ .Values.guestbook.ports.name }}
              containerPort: {{ .Values.guestbook.ports.containerPort }}
              protocol: TCP
          {{- with .Values.guestbook.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.guestbook.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
